Repository kyma-project/template-repository, pull requests merged in 2024-01, with the labels that each got.

#20 Fix title case
  CODE_OF_CONDUCT.md
  docs/user/README.md
Labels: size/XS, lgtm, cla: yes

#24 Improve the hypertext
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: size/S, area/documentation, lgtm, cla: yes

#25 Transition from the GitHub Stale app to GitHub Actions.
  .github/stale.yml
  .github/workflows/stale.yml
Labels: size/M, lgtm, cla: yes
